sudo: required
dist: trusty
language: node_js
node_js:
  - '6.9.5'

addons:
    apt:
      packages:
        - sshpass

before_script:
- export NODE_ENV=prod
- npm install -g karma
- npm install -g typescript
- npm install 
- npm run build
